### ISSUE TITLE
Why is tube a decorator

### ISSUE THREAD

**Issue by Julian** [twisted/tubes#73]
The comment in `tubes.tube.tube` goes into a bit of detail on why it's better than subclassing. That seems great!

But why's it a decorator, instead of just being a function:

```
tube(
    started=lambda self: None,
    stopped=lambda self: None,
    received=lambda self: None,
    inputType=None,
    outputType=None,
) -> class implementing ITube
```

(This would also satisfy #67)

**Comment by glyph** [comment]
I don't think this would be a good idea at all, because

1. it produces a class meant to be directly used without a `class` statement, which is not idiomatic in python (even if it is certainly syntactically possible); this is one of the things that makes `namedtuple` so hard for many to understand
2. one generally wants to put more than `None` into each of these methods, and doing that in an expression is hard
3. what type, exactly, does the `self` in those methods receive?  how is it initialized?  where do I put my `__init__`?

This isn't impossible but it's probably a bad enough idea that i'm closing it for now.

**Comment by Julian** [comment]
I'm not sure I've ever heard that feedback about namedtuple. namedtuple is bad and strangely implemented, I don't think there's anything really wrong with it's structure -- but probably I'm the wrong person to ask then, because if you'd like an example of this sort of API, `jsonschema.validators.create` is one.

As an example of something I've just this second written using the existing tooling, `receiver()(lambda item: [self.do_something_with(item)])` is currently what seems to be the "nicest" inline way to do that. Maybe that's good enough though.

And as for 3, the self would be the instance of the ITube, which is basically only there to allow for calling other interface methods, and you you don't get an __init__, if you need to persist state, you'd define an ITube yourself.

**Comment by glyph** [comment]
Even the [official namedtuple documentation](https://docs.python.org/3/library/collections.html#collections.namedtuple) links to this weird recipe: https://code.activestate.com/recipes/577629-namedtupleabc-abstract-base-class-mix-in-for-named/ for a "nicer syntax", and showcases both `Point = namedtuple(...)` and `class Point(namedtuple(...))` versions, with a very minimal explanation of why you need `__slots__` in there.

**Comment by glyph** [comment]
So it's not that people look at namedtuple and explicitly call out "it's confusing" with feedback; they just *get confused* and use it in a few different inconsistent (arguably wrong) ways, because sometimes they subclass it in order to get a `class` statement and sometimes they don't, sometimes they supply `__slots__` and sometimes they don't.

**Comment by glyph** [comment]
If you have a use-case for "let's make this something other than a decorator because I want to express..." then please open a separate ticket for that, I'm not unilaterally opposed to other features that make inline processing easier :)
